version: "3.9"

services:
  hrt-backend:
    build: ./backend
    container_name: hrt-backend
    ports: ["8000:8000"]
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M

  hrt-dash:
    build: ./frontend
    container_name: hrt-dash
    ports: ["80:80"]
    depends_on: [hrt-backend]